#
# Student makefile for cs154 Project 4
#
# For this project we require that your code compiles
# cleanly (without warnings), hence the -Werror option
mysh: mysh.c
	gcc -Wall -Werror -o mysh mysh.c
clean:
	rm -f mysh
